export TF_VAR_tenancy_ocid=ocid1.tenancy.oc1..aaaaaaaa3wlcifoq6kyl4wmfft7xm7ssp4oz67qxl4lulqvpukchlenat5cq
export TF_VAR_user_ocid=ocid1.user.oc1..aaaaaaaat7cwfpl4sd7ymlgnre7ybl3hjfb4x6wmgvwx2wohcpxbkjxh7jta
export TF_VAR_fingerprint=f9:ea:2d:0a:6a:b4:6f:bc:cf:ae:3b:c9:14:dd:81:51
export TF_VAR_region=us-ashburn-1
export TF_VAR_private_key_path=thims_api_key.pem
export TF_VAR_compartment_ocid=ocid1.compartment.oc1..aaaaaaaakqlagjzxpzm54gxnuwqgkhm5pnrmtuolzs6lnhhi2qd2qnmbqkzq
